exclude: ^package.json|package-lock.json/

ci:
  skip: [prettier, eslint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --skip="*/.*,package.json,package-lock.json,*.bib

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.6.0
          - prettier-plugin-tailwindcss@0.1.8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.11.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.11.0
          - eslint-plugin-svelte3@3.4.1
          - "@typescript-eslint/eslint-plugin@5.14.0"
          - "@typescript-eslint/parser@5.14.0"
