baseurl = "/"
enableRobotsTXT = true
googleAnalytics = "UA-150095279-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "rocinante"
title = "Differentiable Mind"

paginate = 6

[markup]
[markup.highlight]
style = "monokailight"
[markup.goldmark.renderer]
unsafe = true

[params]
about = """
A blog for gradient-ascending minds.
"""
favicon = "https://gohugo.io/favicon-16x16.png"
mainSections = ["philosophy", "math", "resources", "statistics"]

[[params.links]]
    [[params.links.link]]
    href = "/Resume.pdf"
    name = "Resume"
    [[params.links.link]]
    href = "https://github.com/chaichontat"
    name = "Github"
    new_tab = true
    [[params.links.link]]
    href = "https://twitter.com/chaichontat"
    name = "Twitter"
    new_tab = true
